###
###
###
echo -e "g3ty0urflush0t5\ng3ty0urflush0t5" | sudo passwd turki.sultan
echo -e "g00dm0rn1ng@h@h@\ng00dm0rn1ng@h@h@" | sudo passwd labeeba.sesay
echo -e "pfcmk3rh@mk3rmkh@m\npfcmk3rh@mk3rmkh@m" | sudo passwd gaitha.rashid
echo -e "7^We9Tv-gV_CEfdf\n7^We9Tv-gV_CEfdf" | sudo passwd qasimli.zahid
echo -e "PHtV4A!bq*@Qhy\nPHtV4A!bq*@Qhy" | sudo passwd faseeha.wahab
echo -e ".YzdCcwD6>f<%9MC\n.YzdCcwD6>f<%9MC" | sudo passwd taaha.sylla
echo -e "VF8r3<V4hqz:fjC\nVF8r3<V4hqz:fjC" | sudo passwd ammaar.massoud
echo -e "Vu&<Bs?8TqqNCD\nVu&<Bs?8TqqNCD" | sudo passwd yoonus.hariri
echo -e "f/?Qc8=B5z=+z7+\nf/?Qc8=B5z=+z7+" | sudo passwd jaadallah.mady
echo -e "u%cypY_Xtc3LGfn\nu%cypY_Xtc3LGfn" | sudo passwd siraaj.shaban
echo -e "jS33WTfV9_z^wvg\njS33WTfV9_z^wvg" | sudo passwd amaan.kaiser
echo -e "2Dha#r*-BMN\n2Dha#r*-BMN" | sudo passwd hissa.akbar
echo -e "yHN^UfZ:EsZ5x\nyHN^UfZ:EsZ5x" | sudo passwd mundhir.ishmael
echo -e "%97/6s@JTtMn?kX\n%97/6s@JTtMn?kX" | sudo passwd sanad.salame
echo -e "LEmdxX%KW9*fU\nLEmdxX%KW9*fU" | sudo passwd kamran.arasi
echo -e "dnNr/tVK/L3_E?\ndnNr/tVK/L3_E?" | sudo passwd miqdaad.hamidi
echo -e "@UGD:85WVLg-\n@UGD:85WVLg-" | sudo passwd naseera.shah
echo -e "#+8_vtDGZ3MuABy\n#+8_vtDGZ3MuABy" | sudo passwd mudrik.kazi
echo -e "YtC%a8GPsM3dpg\nYtC%a8GPsM3dpg" | sudo passwd sabeeka.iman
echo -e "j52MNWP#xzX-B\nj52MNWP#xzX-B" | sudo passwd sufyaan.jafri
echo -e "J:cp/y!+rnZ:7x8\nJ:cp/y!+rnZ:7x8" | sudo passwd ashraf.koroma
echo -e ".Y%2aY2Z*hpL\n.Y%2aY2Z*hpL" | sudo passwd saajid.kamal
echo -e "%jqwJnr3hf?uHU\n%jqwJnr3hf?uHU" | sudo passwd maaiz.sinai
echo -e "bUpF@G~f9s,SRKx\nbUpF@G~f9s,SRKx" | sudo passwd saadiq.hallal
echo -e "uXM29#T5j=kr-\nuXM29#T5j=kr-" | sudo passwd saalih.ismael
echo -e "sB@w6P^7aX3Xkx\nsB@w6P^7aX3Xkx" | sudo passwd huseynov.sahib
echo -e "k4z2y@!w+WCgj5\nk4z2y@!w+WCgj5" | sudo passwd shuaib.baig
echo -e "xH5M42F7+7a/_C\nxH5M42F7+7a/_C" | sudo passwd qutb.tabet
echo -e "rVwk/^N,W6dCN\nrVwk/^N,W6dCN" | sudo passwd zuhriyaa.bey
echo -e "=%yR*Yx2-Kv83QF\n=%yR*Yx2-Kv83QF" | sudo passwd abdul.jaffer
echo -e "$/s4cd/hv,XuwQ\n$/s4cd/hv,XuwQ" | sudo passwd naseem.abad
echo -e "rwCqCaUje33m2/\nrwCqCaUje33m2/" | sudo passwd fahd.baig
echo -e "gC_dwb8w/sQ?%x\ngC_dwb8w/sQ?%x" | sudo passwd huseynov.akif
echo -e "Y4G/Vag_L9rwZ=\nY4G/Vag_L9rwZ=" | sudo passwd naazim.khan
echo -e "^FsX6C:Lb-^NMBGM\n^FsX6C:Lb-^NMBGM" | sudo passwd ahmed.younan
echo -e "v@gxa2FgTyk/h\nv@gxa2FgTyk/h" | sudo passwd rashaa.salim
echo -e "~Nf6rZyf5Cahwb\n~Nf6rZyf5Cahwb" | sudo passwd awad.rashed
echo -e "GWu?ZqG!cz6#5:D\nGWu?ZqG!cz6#5:D" | sudo passwd sabriyya.saidi
echo -e "-g%,ZF_Bp~S_#6U\n-g%,ZF_Bp~S_#6U" | sudo passwd riyaal.tabatabai
echo -e "DySXcB!+DQP3pB\nDySXcB!+DQP3pB" | sudo passwd nabeeha.bina
echo -e "H8Zz4cA5LUe!e-\nH8Zz4cA5LUe!e-" | sudo passwd shama.miah
echo -e "G9P2-tpVa-aL\nG9P2-tpVa-aL" | sudo passwd afnaan.hammad
echo -e "wXn92pGwP9k*JH\nwXn92pGwP9k*JH" | sudo passwd musaaid.ramin
echo -e "FM7,=5ZdHa4uzM\nFM7,=5ZdHa4uzM" | sudo passwd abdullayev.coshgun
echo -e "9~8*_vzmu7HFs3%\n9~8*_vzmu7HFs3%" | sudo passwd manaahil.ishak
echo -e "NR~jgfm%MN*2G7M\nNR~jgfm%MN*2G7M" | sudo passwd baahir.murad
echo -e "WLFUE#WmQ8brfFu\nWLFUE#WmQ8brfFu" | sudo passwd fawzaana.hanif
echo -e ":Hw4hKbgM4u\n:Hw4hKbgM4u" | sudo passwd asmaa.khalaf
echo -e "4eje,2Fpp8.3GCVe\n4eje,2Fpp8.3GCVe" | sudo passwd maariya.abbasi
echo -e "u7kfK.X3SM=q\nu7kfK.X3SM=q" | sudo passwd waddaah.shakoor
echo -e "s,c=D3CfftF^7:^\ns,c=D3CfftF^7:^" | sudo passwd sundus.arafat
echo -e "s3n10r1t1s\ns3n10r1t1s" | sudo passwd shajeea.iqbal
echo -e "Y!zrK9bH*VWtLG\nY!zrK9bH*VWtLG" | sudo passwd aliyev.sahrab
echo -e "TbvHe!24M94~ej\nTbvHe!24M94~ej" | sudo passwd samedova.gunash
